version: '3.8'

services:
  mysqldb:
    container_name: mysql-container
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SkiStationDB
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  SkiStationProject:
    build: .
    restart: always
    image: skiapp
    container_name: skicontar
    ports:
      - "9090:9090"
    depends_on:
      - mysqldb

volumes:
  mysql_data:
